### PR TITLE
Add Linq2DB Converters

### PR DESCRIPTION
**Pull request by viceroypenguin**

### CODE REVIEW

**Comment by SteveDunn** [comment]
Hi @viceroypenguin - thanks for the PR! It looks great. I've never used linq2db, but I can see how useful it is.

**Comment by SteveDunn** [comment]
When I run `Vogen.Examples.exe`, I see the following crash:
```
Vogen.Examples.SerializationAndConversion.EfCoreExamples+TestEntity
Unhandled exception. LinqToDB.LinqToDBException: Database type cannot be determined automatically and must be specified explicitly
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildDataType(SqlDataType type, Boolean forCreateTable)
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildCreateTableFieldType(SqlField field)
```
Any ideas on that one?

**Comment by viceroypenguin** [comment]
Oops! Fixed that in the integration tests and forgot to go back to the examples. 

I'll get back to my computer this eve and fix that, or you can copy from the integration tests under the serializations area.

**Comment by SteveDunn** [comment]
GitHub is struggling with this PR due to the 3,000+ verify files!  I take it that you just run the command to update all of the `*verified*` files (with one of the methods [described here](https://github.com/VerifyTests/Verify/blob/main/docs/clipboard.md))

**Comment by viceroypenguin** [comment]
> GitHub is struggling with this PR due to the 3,000+ verify files!  I take it that you just run the command to update all of the `*verified*` files (with one of the methods [described here](https://github.com/VerifyTests/Verify/blob/main/docs/clipboard.md))

Yup. The permutations area is what changed 2700+ files. File names changed and such because of the new hash from adding the new converter. The rest were because of a new line in the generated files, even when the converter is not used.

**Comment by viceroypenguin** [comment]
@SteveDunn  - Fixed the examples code - it's working now. :)

**Comment by SteveDunn** [comment]
Thank you again for contributing! Much appreciated!

**Pull request merged**
