### PR TITLE
Added explicit cast operators

### PR DESCRIPTION
**Pull request by Herdo**
Implementation of feature request #206

Operators provide a shorter and sometimes more readable way of converting between the underlying type and the value object.
The operator to convert into the value object simply calls the From method internally.
The operator to convert into the underlying type simply returns the Value property.

@SteveDunn If this is desired and the location in each file is OK, I'll make another commit for the tests.

### CODE REVIEW

**Comment by SteveDunn** [comment]
Hi @Herdo - thanks very much for the PR!
All looks good. I was thinking that maybe these should explicit operators should be controlled by a parameter in the [default configuration](https://github.dev/SteveDunn/Vogen/blob/main/src/Vogen.SharedTypes/VogenDefaultsAttribute.cs) or [instance configuration](https://github.dev/SteveDunn/Vogen/blob/main/src/Vogen.SharedTypes/ValueObjectAttribute.cs)

I haven't got particularly strong opinions on this though; adding the explicit operators looks harmless, and for those that don't want them, they don't have to use them. Plus, they'll throw the same exceptions, so safety won't be lost. 
What do you think re. configuring them (and what the defaults should be, on or off)?

**Comment by SteveDunn** [comment]
Quick tip when it comes to the tests: you'll get thousands of Verify test failures as the C# generated will be different to what's expected.
To accept all changes, temporarily uncomment these: `//settings.AutoVerify();` . There's about 3 of them I think.

**Comment by Herdo** [comment]
@SteveDunn Regarding configuration I'm uncertain. From my previous repo I'm a bit biased towards "no config at all" as it is just another way to express the existing operations.
Yet, I see that there might be devs who explicitly do not want to have these operators, for whatever reason.

Thanks for the hint regarding the tests.

**Comment by Herdo** [comment]
@SteveDunn after sleeping a night about it, and having another look at the Customizations and Conversions enums, I'd stick to "no customization".

Conversions seem to be the opt-in to additional dependencies, like EF and JSON libs.

Customization seem to be for handling edge-cases.

**Comment by SteveDunn** [comment]
OK @Herdo - I suppose if people don't want them, they don't have to use them,

Are you happy to do these tests? I can then merge the PR. Or if you prefer, I can add the tests.

Thanks again for the contribution!

**Comment by Herdo** [comment]
@SteveDunn A note regarding running tests locally: These tests depend on culture and machine time zone and may fail depending on settings:
grafik

**Comment by Herdo** [comment]
Snapshots have been updated. I checked a dozen randomly and they seem to be fine.

**Comment by SteveDunn** [comment]
All looks good - thank you very much for the contribution @Herdo ! Much appreciated.

**Comment by SteveDunn** [comment]
> @SteveDunn A note regarding running tests locally: These tests depend on culture and machine time zone and may fail depending on settings: grafik

Thanks for letting me know - have you got an example of a test failure?

**Pull request merged**
