### PR TITLE
Prefer .From method for type conversion

### PR DESCRIPTION
**Pull request by bobstanton**
Prefer the .From method over the private constructor in Type Converters and deserializers so validation is still considered

### CODE REVIEW

**Comment by SteveDunn** [comment]
Looks great, thank you so much @bobstanton !

I'm wondering if we have tests to cover this behaviour. I'm happy to add them, but if you'd prefer then that'd be great too.

Vogen also has the concept of [Normalization](https://github.com/SteveDunn/Vogen/wiki/Normalization) - so some tests that combine the behaviour when deserializing/converting would also be good.

Thanks once again for the PR. As I say, I'm happy to do the tests, or happy to leave to you.

**Comment by Blackclaws** [comment]
So as mentioned in the now linked issue, deserialization should check the value against its list of specified invalid values, otherwise you run into problems where you might very well have serialized an invalid value into the database _by choice_. 

Deserializing an invalid instance should not throw but instead _return_ the instance.

**Comment by SteveDunn** [comment]
Thanks for the report @Blackclaws . As you can see, @bobstanton has kindly been working on this.

I think the only way to truly resolve this is to allow the user to chose, via configuration, if they want to, when deserialzing:

a) throw on all invalid values
b) throw only on values not specified in Instances
c) never throw

I've been torn between these choices for a few years now (in the previous incarnation of Vogen). In the end, I decided it was best all round not to store Value Objects anywhere and just map from primitives to Value Objects at the boundaries of an application.

How are you getting on @bobstanton ?  Let me know if you need some assistance.

Thanks again @Blackclaws , @bobstanton

**Comment by SteveDunn** [comment]
> Sidenote: Wow 4964 files changed, that's a record. Is there any reason why these tests are stored in the repository if they seem to be autogenerated anyway?

Yes, there are several thousand 'snapshot' tests: tests that generate C# code and verify that it's the same as the expected C# code. There's a link to snapshot tests in this Wiki page: https://github.com/SteveDunn/Vogen/wiki/Tests

**Comment by SteveDunn** [comment]
@Blackclaws - it definitely needs to be addressed. I'm happy enough with a breaking change so long as the major version is incremented. As for the default behaviour... That's a tough one to answer! 🤔

**Comment by viceroypenguin** [comment]
I would argue that part of the reason there's ambiguity in the right answer is because it depends on the data architecture of the application. In some cases, you want to have data validated on serialization, in other cases you want to avoid it. As an example of this ambiguity: if you take data in to an API via json, then you want the values to be validated on deserialization, but if you put it in the database (as stated above), then you don't. 

Without any ability to provide a parameter at the time of deserialization, I would argue that the answer should be either a) configuration option in the attribute to allow whether to validate or not on deserialization; or b) provide two serializers, one with validation, one without, and let consumers apply the right one to the serializer list of STJ/NJ options.

**Comment by Blackclaws** [comment]
> I would argue that part of the reason there's ambiguity in the right answer is because it depends on the data architecture of the application. In some cases, you want to have data validated on serialization, in other cases you want to avoid it. As an example of this ambiguity: if you take data in to an API via json, then you want the values to be validated on deserialization, but if you put it in the database (as stated above), then you don't.
> 
> Without any ability to provide a parameter at the time of deserialization, I would argue that the answer should be either a) configuration option in the attribute to allow whether to validate or not on deserialization; or b) provide two serializers, one with validation, one without, and let consumers apply the right one to the serializer list of STJ/NJ options.

I would agree that this is partially the reason. One additional problem is that you might actually have a change in what data your application considers valid.

As a constructed example. Lets say you did not define any constraints on an Age ValueObject. You then persisted a couple of those into the database with negative numbers. Now you defined an additional constraint that Age must not be negative. Now you end up with a bunch of data that is invalid on de-serialization (and can't be mapped to specific invalid values, leading again to the problematic always need to check before use).

One might argue this is something that should have been fixed by a migration and it actually _should_ throw because in my eyes a ValueObject with a Validator attached makes a strong guarantee to the application that any instance of this object will be valid according to the constraints set. 

In most cases providing two versions of deserializers is not really feasible as they are oftentimes registered with attributes themselves. I think configuring this behavior on the attribute itself would suffice and leave it up to the user.

**Comment by SteveDunn** [comment]
I'll merge this PR that @bobstanton kindly provided as it provides consistency (some were using the private constructor and some were using `From` - i.e. some were validated and some weren't).

I'll then provide an attribute parameter that can be specified globally and overridden locally, that specifies the stricness of deserialization, something like:

`AllowAnything` - does no validation at all - anything is allowed in
`AllowValid` - just runs user validation
`AllowValidAndKnownInstances` - compares to any instances specifies and then runs user validation

For the situation where instance values can change and we might be left data in the database that can never be deserialized, then we'll provide a hook in the form of a method that takes precendence over everything else, e.g.

```
private static DeserializationChoice OnDeserialization(IncomingSource incomingSource, int incomingValue) {
    return DeserializationChoice.Accept(); -- accept the value
    return DeserializationChoice.Reject(); - reject the value
    return DeserializationChoice.ChangeTo("0"); - changes the value to this (with no further valdation)
}
```

**Comment by viceroypenguin** [comment]
That looks like a good solution to me! :)

**Pull request merged**
