### PR TITLE
Add IEquatable of underlying type to classes and structs.

### PR DESCRIPTION
**Pull request by danielcweber**
For classes and structs, Equals() for the underlying type is already implemented, so we get an IEquatable implementation for free.

### CODE REVIEW

**Comment by SteveDunn** [comment]
Thank you very much for the contribution @danielcweber ! Looks like a great idea.  I'll get that merged in for the next release.

**Comment by danielcweber** [comment]
I'll fix the changed snapshots shortly. Testing locally is a bit noisy due to a lot of tests failing because I'm in a different time zone, got a different decimal separator etc.

**Comment by SteveDunn** [comment]
> I'll fix the changed snapshots shortly. Testing locally is a bit noisy due to a lot of tests failing because I'm in a different time zone, got a different decimal separator etc.

Yeah, sorry about that. I've been trying to fix some of them. I think I've had succes fixing the number ones. I've found it quite tricky trying to get my machine into a state where I can reproduce the test failures, so if you're able to fix those, then that would be superb!

Thanks again for your contribution!

**Comment by SteveDunn** [comment]
This might save a bit of time with the snapshots.  Basically, if your change results in 5,000+ snapshot files changing, you do this from the command line:

`dotnet msbuild /p:DefineConstants=AUTO_VERIFY ; dotnet test --no-build`

This accepts all changes to the snapshots, but of course, we need a certain amount of confidence first that the changes are correct.

**Comment by SteveDunn** [comment]
Great stuff - thank you again for your helping! 👍

**Comment by danielcweber** [comment]
>This might save a bit of time with the snapshots. Basically, if your change results in 5,000+ snapshot files changing, you do this from the command line:

>dotnet msbuild /p:DefineConstants=AUTO_VERIFY ; dotnet test --no-build

I kind of did that by temporarily defining the directive in directory.props, however, there's still a lot of diff-windows opening during a test run. Not all tests are covered by AUTO_VERIFY.

**Pull request merged**
