### PR TITLE
fix: source generated partials when using attributes derived from ValueObjectAttribute<T>

### LINKED ISSUE #319: Attributes derived from ValueObjectAttribute<T> don't generate source
### Describe the bug

When using a custom generic attribute derived from `ValueObjectAttribute<T>`, no source code is generated. This only happens in .NET 7 because of the usage of the C# 11 generic attributes language feature.

### Steps to reproduce

1. Create a .NET 7 console app and add the `Vogen` package (tested with `3.0.8`)
2. Create an attribute class that derives from `ValueObjectAttribute<T>`
```csharp
public class MyCustomVoAttribute<T> : ValueObjectAttribute<T> { }
```
3. Apply attribute to a VO struct
```csharp
[MyCustomVoAttribute<int>]
public partial struct SomeValueObject { }
```
4. Attempt to create a new instance of the VO from the main method
```csharp
var x = SomeValueObject.From(2);
Console.WriteLine(x.ToString());
```
5. Build the project

### Expected behaviour

The source generator should create a `*.g.cs` file containing the other part of the `SomeValueObject` struct. Instead, nothing is generated and the build fails due to `SomeValueObject.From` being missing.

### PR DESCRIPTION
**Pull request by jammehcow**
This PR aims to fix #319 where struct/class partials were not being generated when using custom attributes inheriting `ValueObjectAttribute<T>`. Root cause of this is explained in this comment: https://github.com/SteveDunn/Vogen/issues/319#issuecomment-1367023381

TODO:
 - [x] Add addition `BaseType` check on attribute's `BaseType`
 - [x] Snapshot test to ensure custom attributes derived from `ValueObjectAttribute<T>` generate the same source code as direct usage of `ValueObjectAttribute<T>`

### CODE REVIEW

**Comment by jammehcow** [comment]
@SteveDunn I see that the snapshot tests for generic attributes have been commented out. Would you be okay with me adding them back, potentially cleaning them up (if they're missing anything), and adding my derived attribute test to it? Shouldn't be too out of scope of this PR.

**Comment by jammehcow** [comment]
Holding off on this PR until #322 is completed

**Comment by SteveDunn** [comment]
> @SteveDunn I see that the snapshot tests for generic attributes have been commented out. I'll add them back, potentially clean them up (if they're missing anything), and add my derived attribute test to it unless there's a reason for them to be commented out. Shouldn't be too out of scope of this PR.

Yes, I had a *lot* of trouble testing these. I tested them in other way though, like in the consumer tests. I can't remember the exact reason why there were disabled, although it will likely become clear when trying to run them 🙈 !

**Comment by jammehcow** [comment]
Rebased onto `main` after #322 was merged, snapshot test added

**Comment by jammehcow** [comment]
Hey @SteveDunn, in case this got lost in your notifications (or you didn't get any) this is good to go 👌

**Comment by SteveDunn** [comment]
Great - thank you @jammehcow - sorry for the slow reply (it did get lost in a mountain of other notifications this week!)

Really appreciate your help - many thanks.

**Review by SteveDunn — APPROVED** [review]
LGTM!

**Comment by glen-84** [comment]
This doesn't seem to be working for me. Did you try with a non-int value?

I've tried:

```cs
public class IdAttribute : ValueObjectAttribute
{
    public IdAttribute() : base(typeof(long), Conversions.None) { }
}
```

and:

```cs
public class IdAttribute : ValueObjectAttribute<long>
{
    public IdAttribute() : base(Conversions.None) { }
}
```

And the underlying type remains as `int`.

**Comment by jammehcow** [comment]
@glen-84 Well you're right - that snapshot test fails if the type isn't `int`. I'll do some digging and get a fix through, thanks for reporting it!

**Comment by jammehcow** [comment]
I've got semi-working fix generating source for derived types but it requires you to copy the base constructor into your class which isn't ideal. Will try to figure out how to read parameter values of the bass class' constructor tomorrow, and give an explanation of why this feature didn't work.

**Comment by jammehcow** [comment]
In Vogen's current state, parameters passed to the attribute's constructor are extracted from the constructor as constants - not pulled from some post-construction field inside of `ValueObjectAttribute`. Due to this, passing values to the base class' constructor without specifying them in the derived attribute's constructor does nothing so to use derived attributes you must set your default parameter values in the class' constructor. I did find out that parameters passed to base constructors can't be inferred at compile time like Vogen does to top level attribute constructors. 

There's a small fix required to extract generic type values & parameters from derived attributes which I'll add today, as well as a note in the README about requiring default parameter values in derived constructors. 

I guess the real fix here would be to compile the attribute class if it's not one of Vogen's ones, then extract the values passed to `base` from backing fields. Not sure how viable this is with Roslyn or the potential performance degradation.

**Comment by SteveDunn** [comment]
> @jupjohn @SteveDunn Can I get confirmation this should be working?
> 
> ```csharp
> public class CustomValueObjectAttribute<T> : ValueObjectAttribute<T>
> {
>     public CustomValueObjectAttribute(
>         Conversions conversions = Conversions.Default | Conversions.EfCoreValueConverter,
>         CastOperator toPrimitiveCasting = CastOperator.Implicit,
>         CastOperator fromPrimitiveCasting = CastOperator.Implicit,
>         ComparisonGeneration comparisonGeneration = ComparisonGeneration.Omit)
>     { }
> }
> ```
> 
> This is currently failing with InvalidCastException.
> 
> ```csharp
> [CustomValueObject<Guid>]
> public readonly partial record struct ConversationId
> {
> }
> ```
> 
> ```plaintext
> Generator 'ValueObjectGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'InvalidCastException' with message 'Unable to cast object of type 'System.Int32' to type 'Microsoft.CodeAnalysis.INamedTypeSymbol'.'	
> ```
> 
> Vogen `v4.0.17`

Hi, yes, it should work. The whole deriving from attributes scenario is a bit up in the air. Ideally, people wouldn't derive, and that'd open up the possibility of using a faster Roslyn generator. It'd also make the Vogen code easier. But I can see the compelling reason to derive. 
I'll take a look later on.
Thank you for the big report!

**Comment by jupjohn** [comment]
Not to get too in the weeds of it (and keep in mind I don't know all of the limitations of source generators), but _what if_ that derived attribute complexity was yanked out of the existing generator and moved to something that source generated partials with their corresponding `ValueObjectAttribute` attached. That way, one can focus purely on looking at the base attributes and the other acts as a "translator" of sorts. 

Food for thought - I don't know if you can walk the syntax of another generator's output.

**Comment by SteveDunn** [comment]
Hi @jupjohn - unfortunately, it's not possible to combine or set dependencies on different source generators. There's a thread here: https://github.com/dotnet/roslyn/issues/57239

**Pull request merged**
